name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
      - name: Build and run tests
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          sudo apt-get -yqq install libpq-dev
          echo "> Installing bundler..."
          gem install bundler
          echo "> Installing gems..."
          bundle install --jobs 4 --retry 3
          echo "> Copying config database test..."
          cp config/database.yml.github-actions config/database.yml
          echo "> Initializing DB..."
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rspec